<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="VirtoCommerce.ContentModule.Core" Version="3.221.0" />
    <PackageReference Include="VirtoCommerce.ContentModule.Data" Version="3.221.0" />
    <PackageReference Include="VirtoCommerce.SearchModule.Core" Version="3.221.0" />
  </ItemGroup>

</Project>
