// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace VirtoCommerce.PageBuilderModule.Data.MySql.Migrations
{
    /// <inheritdoc />
    public partial class PageBuilder_SharedComponents : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PageBuilderSharedComponent",
                columns: table => new
                {
                    Id = table.Column<string>(type: "varchar(128)", maxLength: 128, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    StoreId = table.Column<string>(type: "varchar(128)", maxLength: 128, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    Name = table.Column<string>(type: "varchar(128)", maxLength: 128, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    CreatedDate = table.Column<DateTime>(type: "datetime(6)", nullable: false),
                    ModifiedDate = table.Column<DateTime>(type: "datetime(6)", nullable: true),
                    CreatedBy = table.Column<string>(type: "varchar(64)", maxLength: 64, nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    ModifiedBy = table.Column<string>(type: "varchar(64)", maxLength: 64, nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PageBuilderSharedComponent", x => x.Id);
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "PageBuilderSharedComponentAssetReference",
                columns: table => new
                {
                    Id = table.Column<string>(type: "varchar(128)", maxLength: 128, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    SharedComponentId = table.Column<string>(type: "varchar(128)", maxLength: 128, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    NormalizedAssetUrl = table.Column<string>(type: "varchar(2048)", maxLength: 2048, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    NormalizedAssetUrlHash = table.Column<string>(type: "varchar(64)", maxLength: 64, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PageBuilderSharedComponentAssetReference", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PageBuilderSharedComponentAssetReference_PageBuilderSharedCo~",
                        column: x => x.SharedComponentId,
                        principalTable: "PageBuilderSharedComponent",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "PageBuilderSharedComponentContent",
                columns: table => new
                {
                    Id = table.Column<string>(type: "varchar(128)", maxLength: 128, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    ComponentContent = table.Column<string>(type: "longtext", nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PageBuilderSharedComponentContent", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PageBuilderSharedComponentContent_PageBuilderSharedComponent~",
                        column: x => x.Id,
                        principalTable: "PageBuilderSharedComponent",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "PageBuilderSharedComponentReference",
                columns: table => new
                {
                    Id = table.Column<string>(type: "varchar(128)", maxLength: 128, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    PageId = table.Column<string>(type: "varchar(128)", maxLength: 128, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    SharedComponentId = table.Column<string>(type: "varchar(128)", maxLength: 128, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PageBuilderSharedComponentReference", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PageBuilderSharedComponentReference_PageBuilderPage_PageId",
                        column: x => x.PageId,
                        principalTable: "PageBuilderPage",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_PageBuilderSharedComponentReference_PageBuilderSharedCompone~",
                        column: x => x.SharedComponentId,
                        principalTable: "PageBuilderSharedComponent",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateIndex(
                name: "IX_PageBuilderSharedComponent_StoreId",
                table: "PageBuilderSharedComponent",
                column: "StoreId");

            migrationBuilder.CreateIndex(
                name: "IX_PageBuilderSharedComponentAssetReference_NormalizedAssetUrlH~",
                table: "PageBuilderSharedComponentAssetReference",
                column: "NormalizedAssetUrlHash");

            migrationBuilder.CreateIndex(
                name: "IX_PageBuilderSharedComponentAssetReference_SharedComponentId",
                table: "PageBuilderSharedComponentAssetReference",
                column: "SharedComponentId");

            migrationBuilder.CreateIndex(
                name: "IX_PageBuilderSharedComponentAssetReference_SharedComponentId_N~",
                table: "PageBuilderSharedComponentAssetReference",
                columns: new[] { "SharedComponentId", "NormalizedAssetUrlHash" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_PageBuilderSharedComponentReference_PageId",
                table: "PageBuilderSharedComponentReference",
                column: "PageId");

            migrationBuilder.CreateIndex(
                name: "IX_PageBuilderSharedComponentReference_PageId_SharedComponentId",
                table: "PageBuilderSharedComponentReference",
                columns: new[] { "PageId", "SharedComponentId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_PageBuilderSharedComponentReference_SharedComponentId",
                table: "PageBuilderSharedComponentReference",
                column: "SharedComponentId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PageBuilderSharedComponentAssetReference");

            migrationBuilder.DropTable(
                name: "PageBuilderSharedComponentContent");

            migrationBuilder.DropTable(
                name: "PageBuilderSharedComponentReference");

            migrationBuilder.DropTable(
                name: "PageBuilderSharedComponent");
        }
    }
}
