<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <noWarn>1591</noWarn>
    <IsPackable>False</IsPackable>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="VirtoCommerce.AssetsModule.Core" Version="3.400.0" />
    <PackageReference Include="VirtoCommerce.ContentModule.Core" Version="3.401.0" />
    <PackageReference Include="VirtoCommerce.Platform.Core" Version="3.400.0" />
    <PackageReference Include="VirtoCommerce.StoreModule.Core" Version="3.400.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VirtoCommerce.PageBuilderModule.Data\VirtoCommerce.PageBuilderModule.Data.csproj" />
  </ItemGroup>
</Project>