// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace VirtoCommerce.PageBuilderModule.Data.PostgreSql.Migrations
{
    /// <inheritdoc />
    public partial class PageBuilder_LinkedComponents : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PageBuilderLinkedComponent",
                columns: table => new
                {
                    Id = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    StoreId = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    Name = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    ModifiedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    CreatedBy = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    ModifiedBy = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PageBuilderLinkedComponent", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "PageBuilderLinkedComponentContent",
                columns: table => new
                {
                    Id = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    ComponentContent = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PageBuilderLinkedComponentContent", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PageBuilderLinkedComponentContent_PageBuilderLinkedComponen~",
                        column: x => x.Id,
                        principalTable: "PageBuilderLinkedComponent",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "PageBuilderLinkedComponentReference",
                columns: table => new
                {
                    Id = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    PageId = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    LinkedComponentId = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PageBuilderLinkedComponentReference", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PageBuilderLinkedComponentReference_PageBuilderLinkedCompon~",
                        column: x => x.LinkedComponentId,
                        principalTable: "PageBuilderLinkedComponent",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_PageBuilderLinkedComponentReference_PageBuilderPage_PageId",
                        column: x => x.PageId,
                        principalTable: "PageBuilderPage",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "PageBuilderLinkedComponentAssetReference",
                columns: table => new
                {
                    Id = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    LinkedComponentId = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    NormalizedAssetUrl = table.Column<string>(type: "character varying(2048)", maxLength: 2048, nullable: false),
                    NormalizedAssetUrlHash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PageBuilderLinkedComponentAssetReference", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PageBuilderLinkedComponentAssetReference_PageBuilderLinkedC~",
                        column: x => x.LinkedComponentId,
                        principalTable: "PageBuilderLinkedComponent",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_PageBuilderLinkedComponent_StoreId",
                table: "PageBuilderLinkedComponent",
                column: "StoreId");

            migrationBuilder.CreateIndex(
                name: "IX_PageBuilderLinkedComponentReference_LinkedComponentId",
                table: "PageBuilderLinkedComponentReference",
                column: "LinkedComponentId");

            migrationBuilder.CreateIndex(
                name: "IX_PageBuilderLinkedComponentAssetReference_LinkedComponentId",
                table: "PageBuilderLinkedComponentAssetReference",
                column: "LinkedComponentId");

            migrationBuilder.CreateIndex(
                name: "IX_PageBuilderLinkedComponentAssetReference_NormalizedAssetUrl~",
                table: "PageBuilderLinkedComponentAssetReference",
                column: "NormalizedAssetUrlHash");

            migrationBuilder.CreateIndex(
                name: "IX_PageBuilderLinkedComponentAssetReference_LinkedComponentId_~",
                table: "PageBuilderLinkedComponentAssetReference",
                columns: new[] { "LinkedComponentId", "NormalizedAssetUrlHash" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_PageBuilderLinkedComponentReference_PageId",
                table: "PageBuilderLinkedComponentReference",
                column: "PageId");

            migrationBuilder.CreateIndex(
                name: "IX_PageBuilderLinkedComponentReference_PageId_LinkedComponentId",
                table: "PageBuilderLinkedComponentReference",
                columns: new[] { "PageId", "LinkedComponentId" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PageBuilderLinkedComponentAssetReference");

            migrationBuilder.DropTable(
                name: "PageBuilderLinkedComponentContent");

            migrationBuilder.DropTable(
                name: "PageBuilderLinkedComponentReference");

            migrationBuilder.DropTable(
                name: "PageBuilderLinkedComponent");
        }
    }
}
