<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="VirtoCommerce.AssetsModule.Core" Version="3.814.0" />
    <PackageReference Include="VirtoCommerce.ContentModule.Core" Version="3.837.0-alpha.1032-vcst-4500" />
    <PackageReference Include="VirtoCommerce.CustomerModule.Core" Version="3.833.0" />
    <PackageReference Include="VirtoCommerce.Pages.Core" Version="3.810.0" />
    <PackageReference Include="VirtoCommerce.Platform.Core" Version="3.917.0" />
    <PackageReference Include="VirtoCommerce.StoreModule.Core" Version="3.818.0" />
    <PackageReference Include="VirtoCommerce.SearchModule.Core" Version="3.821.0" />
  </ItemGroup>
</Project>