# v2.0.0
name: Build PageBuilder App

inputs:
  githubToken:
    description: "GitHub Token"
    required: true

runs:
  using: composite

  steps:

    - name: Install dependencies for PageBuilder App New
      shell: bash
      working-directory: src/VirtoCommerce.PageBuilderModule.Web/page-builder-new
      run: yarn
      
    - name: Build PageBuilder App New
      shell: bash
      working-directory: src/VirtoCommerce.PageBuilderModule.Web/page-builder-new
      run: yarn build

