import { BlockValuesModel } from '@shared/models';
import { createAction, props } from '@ngrx/store';

import { PageModel } from '../models/page.model';
import { BlockSchema, BlocksSchema } from 'src/app/modules/shared/models';
import { HttpErrorResponse } from '@angular/common/http';

export const addPageItem = createAction('[Page] Add Page Item', props<{ block: BlockValuesModel }>());
export const blocksSchemaFail = createAction('[Page] Blocks Schema Fail', props<{error: HttpErrorResponse}>());
export const blocksSchemaLoaded = createAction('[Page] Blocks Schema Loaded', props<{schema: BlocksSchema}>());
export const clearPageChanges = createAction('[Page] Clear Page Changes');
export const clonePageItem = createAction('[Page] Clone Page Item',
                                props<{ originalBlock: BlockValuesModel, newBlock: BlockValuesModel }>());
export const closeEditors = createAction('[Page] Close Editors');
export const completeEditPageItem = createAction('[Page] Complete Edit Page Item');
export const copyPageItem = createAction('[Page] Copy Page Item', props<{ sourceBlock: BlockValuesModel }>());
export const createPageItem = createAction('[Page] Create Page Item', props<{ newItemSchema: BlockSchema }>());
export const loadBlocksSchema = createAction('[Page] Load Blocks Schema');
export const swapBlocks = createAction('[Page] Swap Blocks', props<{ previousIndex: number, currentIndex: number }>());
export const loadBlocks = createAction('[Page] Load Blocks');
export const loadBlocksFail = createAction('[Page] Load Blocks Fail', props<{ error: HttpErrorResponse }>());
export const loadBlocksSuccess = createAction('[Page] Load Blocks Success', props<{ blocks: BlockValuesModel[] }>());
export const reloadBlocks = createAction('[Page] ReLoad Blocks');
export const reloadBlocksFail = createAction('[Page] ReLoad Blocks Fail', props<{ error: HttpErrorResponse }>());
export const reloadBlocksSuccess = createAction('[Page] ReLoad Blocks Success', props<{ blocks: BlockValuesModel[] }>());
export const moveBlock = createAction('[Page] Move Block', props<{ previousIndex: number, currentIndex: number }>());
export const orderChanged = createAction('[Page] Order Changed', props<{ previousIndex: number, currentIndex: number }>());
export const previewPageItem = createAction('[Page] Preview Page Item', props<{ block: BlockValuesModel }>());
export const previewPageItemOfType = createAction('[Page] Preview Page Item Of Type', props<{ blockSchema: BlockSchema }>());
export const removePageItem = createAction('[Page] Remove Page Item', props<{ block: BlockValuesModel }>());
export const saveBlocks = createAction('[Page] Save Blocks');
export const saveBlocksFail = createAction('[Page] Save Page Fail', props<{ error: any }>());
export const saveBlocksSuccess = createAction('[Page] Save Page Success');
export const selectPageItem = createAction('[Page] Select Page Item', props<{ blockId: number }>());
export const selectSettingsPageItem = createAction('[Page] Select Settings Page Item', props<{ key: string }>());
export const toggleNewBlockPane = createAction('[Page] Toggle New Block Pane', props<{ display: boolean }>());
export const copyToClipboard = createAction('[Page] Copy To Clipboard', props<{ block: BlockValuesModel }>());
export const tryPasteFromClipboard = createAction('[Page] Try Paste From Clipboard');
export const tryPasteFromString = createAction('[Page] Try Paste From String', props<{ value: string }>());
export const showPastePopup = createAction('[Page] Show Paste Popup');
export const updateBlockPreview = createAction('[Page] Update Block Preview', props<{ block: BlockValuesModel }>());
export const updatePageItem = createAction('[Page] Update Page Item', props<{ block: BlockValuesModel }>());
export const updatePageSettings = createAction('[Page] Update Page Settings', props<{ settings: BlockValuesModel }>());
export const toggleItemVisibility = createAction('[Page] Toggle Item Visibility', props<{ block: BlockValuesModel }>());
export const markSectionHoveredInPreview = createAction('[Page] Mark Section Hovered In Preview', props<{ blockId: number }>());
export const highlightInPreview = createAction('[Page] Highlight In Preview', props<{ block: BlockValuesModel }>());
export const setEditorMode = createAction('[Page] Set Editor Mode', props<{ mode: string }>());
