# v1.1.3
name: Module CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'build/**'
      - 'README.md'
      - 'LICENSE'
    branches:
      [master, dev]
  pull_request:
    branches:
      [master, dev]
    paths-ignore:
      - 'docs/**'
      - 'build/**'
      - 'README.md'
      - 'LICENSE'
    
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
      BLOB_SAS: ${{ secrets.BLOB_TOKEN }}
      VERSION_SUFFIX: ""

    steps:

      - name: Set up Node 16
        uses: actions/setup-node@v2
        with:
            node-version: '16'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install VirtoCommerce.GlobalTool
        run: dotnet tool install --global VirtoCommerce.GlobalTool

      - name: Get Image Version
        uses: VirtoCommerce/vc-github-actions/get-image-version@master
        id: image
        
      - name: Set VERSION_SUFFIX variable
        run: |
            echo "VERSION_SUFFIX=${{ steps.image.outputs.suffix }}" >> $GITHUB_ENV
 
      - name: Add version suffix
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: VirtoCommerce/vc-github-actions/add-version-suffix@master
        with:
          versionSuffix: ${{ env.VERSION_SUFFIX }}

      - name: Setup Git Credentials
        if: ${{ github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master' }}
        uses: VirtoCommerce/vc-github-actions/setup-git-credentials-github@master
        with: 
          githubToken: ${{ secrets.REPO_TOKEN }}

      - name: Clone page-builder
        if: ${{ github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master' }}
        run: |
            git clone https://github.com/VirtoCommerce/template-builder.git --branch dev
            cd ./template-builder/src/builder
            npm i
            npx ng build ngv-markdown
            npm run build
            cd ../bridge
            npm i
            npm run build:prod
            cd ../preview
            npm i
            npm run build:prod
            cd ../../../
            mkdir ./src/VirtoCommerce.PageBuilderModule.Web/Content/
            mkdir ./src/VirtoCommerce.PageBuilderModule.Web/Content/builder/
            mkdir ./src/VirtoCommerce.PageBuilderModule.Web/Content/bridge/
            mkdir ./src/VirtoCommerce.PageBuilderModule.Web/Content/preview/
            cp -R ./template-builder/src/builder/dist/template-builder/* ./src/VirtoCommerce.PageBuilderModule.Web/Content/builder/
            cp -R ./template-builder/src/bridge/dist/* ./src/VirtoCommerce.PageBuilderModule.Web/Content/bridge/
            cp -R ./template-builder/src/preview/dist/* ./src/VirtoCommerce.PageBuilderModule.Web/Content/preview/

      - name: Packaging
        run: vc-build Compress -skip Test

      - name: Publish to Blob
        if: ${{ github.ref == 'refs/heads/dev' }}
        id: blobRelease
        uses: VirtoCommerce/vc-github-actions/publish-blob-release@master
        with:
          blobSAS: ${{ secrets.BLOB_TOKEN }}
        
      - name: Publish Github Release
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          changelog: ${{ steps.changelog.outputs.changelog }}
        uses: VirtoCommerce/vc-github-actions/publish-github-release@master
